task3
KondrashovKonstantin/virginhotel pull request #1
Opened 2020-11-23 14:27 UTC by KondrashovKonstantin

2021-02-03 12:53 UTC, ssstelsss requested changes

2021-02-03 12:53 UTC, ssstelsss commented on components/Comment/index.js
> +export default observer(function Note ({ avaUri, author, date, text }) {
function Comment

2021-02-03 12:53 UTC, ssstelsss commented on components/Comment/index.js
> +export default observer(function Note ({ avaUri, author, date, text }) {
следи за тем чтобы имя функции и название файла совпадали

2021-02-03 12:53 UTC, ssstelsss commented on components/Event/index.js
> +  console.log(image)
поубирай логи

2021-02-03 12:53 UTC, ssstelsss commented on components/Event/index.js
> +export default observer(function Event ({ startDate = new Date(), finishDate = new Date(), title, location, withImage = false, image }) {
думаю будет достаточно передавать image, если он передан, то значит и изображение есть. withImage - излишество

2021-02-03 12:53 UTC, ssstelsss commented on components/Event/index.js
> +    if withImage
давай проверять просто image

2021-02-03 12:53 UTC, ssstelsss commented on components/Event/index.js
> +        Div.imageWrapp
Div.imageWrap

2021-02-03 12:53 UTC, ssstelsss commented on components/Event/index.js
> +          Span(styleName='red')= getStringDay(startDate) +'\n' + getStringMonth(startDate)
тут можно написать Span.red будет такой же эффект. Но это не обязательно

2021-02-03 12:53 UTC, ssstelsss commented on components/Event/index.js
> +  let formatTime = (date) => {
кажется toLocalTimeString даст такой же результат
![image](https://user-images.githubusercontent.com/58818714/106744826-5034cb80-6631-11eb-9971-53f2dbae6222.png)

2021-02-03 12:53 UTC, ssstelsss commented on main/Layout/index.js
> +const BASE_URL = 'http://localhost:3010/public/'
бери BASE_URL из @env, а не пиши сам

2021-02-03 12:53 UTC, ssstelsss commented on main/Layout/index.js
> +            size='xl')
) на новую строку

2021-02-03 12:53 UTC, ssstelsss commented on main/Layout/index.styl
> +  flex-direction row
используй компонент Row и этот стиль будет не нужен

2021-02-03 12:53 UTC, ssstelsss commented on main/Layout/index.styl
> +  display:none
: не нужно

2021-02-03 12:53 UTC, ssstelsss commented on main/Layout/index.styl
> +  display: none
тоже

2021-02-03 12:53 UTC, ssstelsss commented on main/Layout/index.styl
> +    +wide()
лишний таб

2021-02-03 12:53 UTC, ssstelsss commented on main/pages/PHome/Navbar/HotelEvents/index.js
> +      for item,i in events
each

2021-02-03 12:53 UTC, ssstelsss commented on main/pages/PHome/Navbar/TeamEvents/index.js
> +      for item, i in events
each

2021-02-03 12:53 UTC, ssstelsss commented on main/pages/PHome/Navbar/TeamEvents/index.js
> +        Div.event(styleName=i==={first:!i})
добавь key

2021-02-03 12:53 UTC, ssstelsss commented on main/pages/PHome/Navbar/HotelEvents/index.js
> +        Div.event(styleName={first:!i})
key

2021-02-03 12:53 UTC, ssstelsss commented on main/pages/PHome/Navbar/index.js
> +        Divider(style={width:'60px'})
стили в файл стилей, тут тольок имя класса

2021-02-03 12:53 UTC, ssstelsss commented on main/pages/PHome/Navbar/index.js
> +        Divider(style={width:'60px'})
same

2021-02-03 12:53 UTC, ssstelsss commented on main/pages/PHome/Notes/index.js
> +        Note(
key, each

2021-02-03 12:53 UTC, ssstelsss commented on main/pages/PHome/Options/index.js
> +  const [options, toggleOptions] = useState(false)
setOptions

2021-02-03 12:53 UTC, ssstelsss commented on main/pages/PHome/Options/index.styl
> +    margin: 0
: не надо

2021-02-03 12:53 UTC, ssstelsss commented on main/pages/PHome/index.styl
> +
лишние абзацы

2021-02-03 18:15 UTC, KondrashovKonstantin commented on components/Event/index.js
> +  let formatTime = (date) => {
Нет не одинаково, toLocalTimeString я там ниже юзал, а в том блоке ивентов нужно было pm без пробела и с маленькой буквы (По макету)

2021-02-20 10:43 UTC, lupenq commented on components/Comment/index.styl
> +    position relative
position relative стоит по умолчанию у каждого элемента. Я уже писал тебе такой комментарий)
После каждого коммента проходись по проекту и исправляй, и по другим проектам тоже

2021-02-20 10:43 UTC, lupenq commented on components/Comment/index.styl
> +    border none
Можно просто баттону дать variant='text'

2021-02-20 10:44 UTC, lupenq commented on components/Event/index.js
> +  let formatTime = (date) => {
мог просто отойти от макета, ну или захардкодить строкой все эти времена, чем городить подобное

2021-02-20 10:49 UTC, lupenq commented on main/Layout/index.js
> +          ImageBackground.back(source={uri:back} imageStyle={height:'820px'})
imageStyleName=

2021-02-20 10:50 UTC, lupenq commented on main/Layout/index.styl
> +  border none
same

2021-02-20 11:03 UTC, lupenq commented on main/pages/PHome/Notes/index.js
> +import './index.styl'
пиши импорт стилей последним

2021-02-20 11:04 UTC, lupenq commented on main/pages/PHome/Suggestion/index.styl
> +.title
лишние 2 строчки

2021-02-20 11:48 UTC, lupenq commented
А где компонент с юзером в шапке справа?

2021-09-06 20:16 UTC, merged